### ISSUE TITLE
Changes to configuration files are not read unless `isort: Restart`

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-isort#107] opened 2022-09-10 00:16 UTC
I added

```diff
# setup.cfg
[isort]
profile = black
+ known_third_party = wandb
```

but this extension continued to sort `wandb` as 1st party (due to log directory of same name in package) until I ran the command [`isort`: Restart](https://github.com/microsoft/vscode-isort#commands).

**Example**

Expected
```py
import os

import pandas as pd
import wandb
```

Actual

```py
import os

import pandas as pd

import wandb
```

**Comment by karthiknadig** [comment] 2022-09-12 17:45
Currently, we do automatic restart when settings are updated in settings.json. We should be able to add file watching to monitor `setup.cfg` and restart `isort`.

Note that the fact that setup.cfg changes are not getting picked up is actually `isort` issue. In the server, we load `isort` once and it seems to cache the settings that it reads the first time. The restart is a workaround to get `isort` to reload new settings.

**Comment by brettcannon** [comment] 2022-10-17 17:25
We should make sure to check where isort reads its configuration from to make sure we don't miss anything as I'm sure there are more places than just `setup.cfg` (e.g. `pyproject.toml`).

**Comment by janosh** [comment] 2022-10-17 17:29
[isort supports 5 config files](https://pycqa.github.io/isort/docs/configuration/config_files.html):

- `.isort.cfg`
- `pyproject.toml`
- `setup.cfg`
- `tox.ini`
- `.editorconfig`

`setup.cfg` and `pyproject.toml` probably combine to +95% market share.

**Comment by jmichalicek** [comment] 2022-11-09 21:15
This is definitely not working with pyproject.toml. isort used to work just fine, then the preview version of this extension was forced on me and now isort is not sorting correctly from vscode. Works just fine if I manually run it from the command line.

**Comment by karthiknadig** [comment] 2022-11-09 21:30
@jmichalicek You can try this `"isort.args": ["--settings-path", "${workspaceFolder}/pyproject.toml"]` and see if that helps. 

This particular issue is about reloading isort if there is a change to one of the settings files.

**Comment by wonder-mice** [comment] 2022-11-10 22:02
That was my major issue with isort - to figure out how to make it use the latest config. Especially painful when creating a new isort config and need to iterate quickly.

**Comment by karthiknadig** [comment] 2022-11-11 19:03
Duplicate of  https://github.com/microsoft/vscode-isort/issues/71

**Closed by karthiknadig** 2022-11-11 19:03 UTC
Labels: bug, needs PR
