### ISSUE TITLE
Extension not support python < 3.10 because use future annotation format

### ISSUE THREAD

**Issue by dc-avasilev** [microsoft/vscode-isort#168] opened 2022-11-22 10:56 UTC
its a problem for centos 7 where python is old version by default
```
Name: isort
Module: isort
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Info  - 1:44:10 PM] Connection to server got closed. Server will restart.
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Info  - 1:44:10 PM] Connection to server got closed. Server will restart.
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Info  - 1:44:10 PM] Connection to server got closed. Server will restart.
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Info  - 1:44:10 PM] Connection to server got closed. Server will restart.
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Error - 1:44:10 PM] Connection to server got closed. Server will not be restarted.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:45:26 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:45:27 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:45:27 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:45:27 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Error - 1:45:27 PM] Connection to server got closed. Server will not be restarted.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:47:39 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:47:39 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:47:40 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:47:40 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Error - 1:47:40 PM] Connection to server got closed. Server will not be restarted.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 177, in <module>
    source: str = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:48:08 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 177, in <module>
    source: str = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:48:08 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 177, in <module>
    source: str = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:48:09 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 177, in <module>
    source: str = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:48:09 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/root/.vscode-server/extensions/ms-python.isort-2022.9.13221008/bundled/tool/utils.py", line 177, in <module>
    source: str = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Error - 1:48:09 PM] Connection to server got closed. Server will not be restarted.

```

**Comment by eleanorjboyd** [comment] 2022-11-22 18:51
Hello! We have received this issue and will look into it soon, thanks!

**Comment by brettcannon** [comment] 2022-11-29 17:52
Closing as a duplicate of https://github.com/microsoft/vscode-isort/issues/152 .

**Closed by brettcannon** 2022-11-29 17:52 UTC
Labels: triage-needed
