### ISSUE TITLE
The isort server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by QHPHBias** [microsoft/vscode-isort#189] opened 2022-12-15 02:14 UTC
I started isort locally for automatic formatting. However, the service won't start. Here is my error log:

Traceback (most recent call last):
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\server.py", line 40, in <module>
    import utils
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\utils.py", line 33, in <module>
    for p in (as_list(site.getsitepackages()) + as_list(site.getusersitepackages()))
AttributeError: module 'site' has no attribute 'getsitepackages'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:11:41] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\server.py", line 40, in <module>
    import utils
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\utils.py", line 33, in <module>
    for p in (as_list(site.getsitepackages()) + as_list(site.getusersitepackages()))
AttributeError: module 'site' has no attribute 'getsitepackages'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:11:41] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\server.py", line 40, in <module>
    import utils
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\utils.py", line 33, in <module>
    for p in (as_list(site.getsitepackages()) + as_list(site.getusersitepackages()))
AttributeError: module 'site' has no attribute 'getsitepackages'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:11:42] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\server.py", line 40, in <module>
    import utils
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\utils.py", line 33, in <module>
    for p in (as_list(site.getsitepackages()) + as_list(site.getusersitepackages()))
AttributeError: module 'site' has no attribute 'getsitepackages'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:11:42] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\server.py", line 40, in <module>
    import utils
  File "c:\Users\qhph\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\utils.py", line 33, in <module>
    for p in (as_list(site.getsitepackages()) + as_list(site.getusersitepackages()))
AttributeError: module 'site' has no attribute 'getsitepackages'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Error - 10:11:42] Connection to server got closed. Server will not be restarted.

**Comment by QHPHBias** [comment] 2022-12-15 02:15
Environment: Windows10 Python 3.7.0rc1 VSCode1.74.1

**Comment by brettcannon** [comment] 2022-12-15 17:43
I am going to assume this is a duplicate of https://github.com/microsoft/vscode-isort/issues/152 , but if it isn't then please let us know and we can re-open this to try and figure what's going on further.

**Closed by brettcannon** 2022-12-15 17:43 UTC
Labels: triage-needed
