### ISSUE TITLE
`vscode-isort` ignores `isort` settings in `pyproject.toml`

### ISSUE THREAD

**Issue by garysassano** [microsoft/vscode-isort#272] opened 2023-04-23 08:07 UTC
I like to have all my  project's configuration inside the `pyproject.toml` instead of relying on the IDE, since other people may have that configured differently.

This is why I don't use this `settings.json` for my VS Code installation:
```
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
  },
  "isort.args":["--profile", "black"],
```

but just:
```
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
  },
```
Because in my `pyproject.toml` I have:
```
[tool.black]
line-length = 100

[tool.isort]
profile = "black"
```

The problem is that, when VS Code runs its internal `source.organizeImports` (which we know being just a masked `isort`) on save, it will completely ignore the settings specified in the `pyrproject.toml`.

On the other hand, when VS Code runs the `black` command for you on save, it will evaluate all settings you specified in your `pyproject.toml`, and so in my case it will set `line-length = 100` correctly. The same thing doesn't apply to the `isort` that VS Code runs behind the scenes, which completely ignores any setting you may have in your `pyrproject.toml`.

**Comment by karthiknadig** [comment] 2023-07-12 19:45
Duplicate of https://github.com/microsoft/vscode-isort/issues/53

This is an issue with `isort` itself. it is not released yet by isort: https://github.com/PyCQA/isort/pull/1992
see https://github.com/PyCQA/isort/blob/main/CHANGELOG.md

**Closed by karthiknadig** 2023-07-12 19:45 UTC
Labels: triage-needed
