### ISSUE TITLE
The isort server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode-isort#128] opened 2022-10-21 01:59 UTC
Type: <b>Bug</b>

Not sure what is causing the problem.

# Log
```py
Traceback (most recent call last):
  File "/home/scarf/.vscode/extensions/ms-python.isort-2022.3.12911018/bundled/tool/server.py", line 41, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "/home/scarf/.vscode/extensions/ms-python.isort-2022.3.12911018/bundled/libs/pygls/lsp/__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "/home/scarf/.vscode/extensions/ms-python.isort-2022.3.12911018/bundled/libs/pygls/lsp/types/__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "/home/scarf/.vscode/extensions/ms-python.isort-2022.3.12911018/bundled/libs/pygls/lsp/types/general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "/home/scarf/.vscode/extensions/ms-python.isort-2022.3.12911018/bundled/libs/pygls/lsp/types/language_features/__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "/home/scarf/.vscode/extensions/ms-python.isort-2022.3.12911018/bundled/libs/pygls/lsp/types/language_features/call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "/home/scarf/.vscode/extensions/ms-python.isort-2022.3.12911018/bundled/libs/pydantic/main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scarf/.vscode/extensions/ms-python.isort-2022.3.12911018/bundled/libs/pydantic/utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "/home/scarf/.asdf/installs/python/3.11.0rc2/lib/python3.11/inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x7ffa70a45800>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 오전 10:55:50] Connection to server got closed. Server will restart.
```

Extension version: 2022.3.12931038
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.15.0-52-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.72GB (23.06GB free)|
|Process Argv|--unity-launch --crash-reporter-id b0fe70dc-73b5-44f5-a8cc-3807703c7d9c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by karthiknadig** [comment] 2022-10-21 02:02
@scarf005 Python 3.11 is not supported yet. This is caused by an issue in underlying library https://github.com/openlawlibrary/pygls/issues/234

Duplicate of https://github.com/microsoft/vscode-isort/issues/97

**Closed by karthiknadig** 2022-10-21 02:02 UTC
Labels: triage-needed
