### ISSUE TITLE
Provider throwing errors on vscode 1.73.0

### ISSUE THREAD

**Issue by mthanded** [microsoft/vscode-isort#142] opened 2022-11-05 17:11 UTC
Since the newest vscode release I have had some issues getting the plugin to run correctly. From a clean plugin install I am seeing this in the extension host log on an m1 mac 

```
2022-11-05 12:59:18.676 [error] [ms-python.isort] provider FAILED
2022-11-05 12:59:18.676 [error] TypeError: Cannot read properties of null (reading 'map')
	at g (/Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:214932)
	at Object.asCodeAction (/Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:225872)
	at /Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:154586
	at async x.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:43007)
```

If I change the isort to use the environment's isort I get
```2022-11-05 13:02:08.107 [error] [ms-python.isort] provider FAILED
2022-11-05 13:02:08.107 [error] TypeError: Cannot read properties of null (reading 'map')
	at g (/Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:214932)
	at Object.asCodeAction (/Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:225872)
	at /Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:154586
	at async x.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:43007)
2022-11-05 13:02:08.895 [error] Error: write after end
	at new NodeError (node:internal/errors:371:5)
	at _write (node:internal/streams/writable:319:11)
	at Writable.write (node:internal/streams/writable:334:10)
	at /Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:126879
	at new Promise (<anonymous>)
	at u.write (/Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:126797)
	at m.doWrite (/Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:116401)
	at /Users/mt/.vscode/extensions/ms-python.isort-2022.4.0/dist/extension.js:1:116296
	at runNextTicks (node:internal/process/task_queues:61:5)
	at process.processImmediate (node:internal/timers:437:9)
```

My settings.json 
```
{
    "editor.formatOnSave": true,
    "[python]": {
        "editor.wordBasedSuggestions": false
    },
    "python.formatting.provider": "black",
    "isort.check": true,
}
```

**Comment by mthanded** [comment] 2022-11-05 18:12
A little self debugging here. If `--verbose` is passed to isort the output of the verbose isort command ends up in the file instead of the transformed sort order

```

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.10.1

from-type place_module for typing returned STDLIB
else-type place_module for uvicorn returned THIRDPARTY
from-type place_module for aiokafka returned THIRDPARTY
from-type place_module for fastapi returned THIRDPARTY
Fixing /Users/mt/Projects/isort_tests/test_isort/test_isort/test.py
```

**Comment by karthiknadig** [comment] 2022-11-05 20:18
Duplicate of https://github.com/microsoft/vscode-isort/issues/77 Should not impact how it works.

**Closed by karthiknadig** 2022-11-05 20:18 UTC
Labels: triage-needed
